QDRANT_API = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.-7invO9MexiZk5IFjqH83t_5yErHrPkVIBSdxj0FR6A"
QDRANT_URL = "https://f34ed4c0-8bf2-4f62-8d2c-63860393cdce.us-east4-0.gcp.cloud.qdrant.io"
HF_API_KEY = "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"